### PR TITLE
Update webpack and webpack-dev-server

### PR DESCRIPTION
**Pull request by haydenlinder**
Ticket: https://linear.app/superhuman/issue/DESK-5868/upgrade-dependent-packages

`webpack-dev-server` v3 -> v4 migration guide: https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

`webpack` v4 -> v5 migration guide: https://webpack.js.org/migrate/5/

| Before | After |
|--|-|
| before | after |

### CODE REVIEW

**Comment by haydenlinder** [comment]
Running against the `website`, I can't seem to get past a hang at `Compiling 99% - cache` in the browser when running this sequence:

1. In `zen`
```
git checkout webpack
git pull origin webpack
yarn link
yarn start
```

2. In `website`
```
git checkout webpack
git pull origin webpack
yarn link @superhuman/zen
yarn zen
```

3. Go to `http://localhost:3100/`

Here's what I've tried:

1. Migrate to `webpack@latest` here and in [website](https://github.com/superhuman/zen/pull/45).
2. Run `npm ls webpack` and upgrade anything red to `latest` here and in `website`.
3. Followed migration guides for webpack upgrade and dependent upgrades here and in `website`.
4. Pinned `webpack-sources@^2.0.0` in package.json to avoid `Content and Map of this Source is not available`. This fixed the error, but the browser is still hanging at 99% - cache.

**Comment by keedyc** [comment]
I haven't looked at these changes in detail yet, but I wonder whether we can address any of `webpack-dev-server`'s vulnerabilities by upgrading to a version that doesn't require Webpack 5, like [3.11.2](https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.2). That approach jumps to mind for a few reasons:
1. Upgrading to Webpack 5 feels relatively time-consuming and risky.
2. If we keep migrating the site to Next.js (TBD based on Marketing/Design input), we might not need a manual upgrade to Webpack 5. Next's own use of Webpack 5 should be adequate.

**Comment by haydenlinder** [comment]
@keedyc thanks for the input - that sounds like a good idea. 

I'll put up a new PR for the website repo and see what I can update without touching webpack itself.

**Comment by haydenlinder** [comment]
https://github.com/superhuman/website/pull/1259 should solve all but 1 high/critical vulnerability on `website`.

**Pull request closed without merging**
